name: Git Push Example

on:
  push:
    branches:
      - develop

jobs:
  push-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código-fonte
        uses: actions/checkout@v3

      - name: Criar um novo arquivo para commit
        run: |
          echo "Arquivo gerado automaticamente" > novo-arquivo.txt
          git add novo-arquivo.txt
          git commit -m "Adicionando novo arquivo automaticamente"

      - name: Git Push Action
        uses: x-actions/git-push@v1.0
        with:
          GITHUB_EMAIL: "bastcord@gmail.com"
          GITHUB_USERNAME: "09437736790"
          PUBLISH_REPO: "https://x-access-token:${{ secrets.PERSONALTOKEN }}@github.com/09437736790/cat5.git"
          PUBLISH_BRANCH: "develop"
          PUBLISH_DIR: "."  # Publica todas as alterações do diretório raiz
